import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "@/app/globals.css";
import {AppProps} from "next/app";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default ({Component, pageProps}: AppProps) => {
  return (
    <Component {...pageProps} />
  );
}
